#!/bin/bash  
# record: 以一小时为间隔，访问MySQL数据库，查询website表的行数，并输出到标准输出中，


# 等待整点的到来
wait_for_hour(){

	# 每次休眠20秒，直到遇到整点
	while [[ true ]]; do
		if [[ "$(date +%M)" == "00" ]]; then
			break
		else 
			sleep 20s	

		fi
	done
	run
}

run(){
	spy
	sleep 58m
	wait_for_hour

} 
# 执行对数据库的访问
spy(){

	format="%F %T"
	timestamp=$(date +"$format")

	echo $timestamp
	for (( i=0; i<20; i++)); do echo -n "-"; done
	echo

	mysql -h 123.56.165.238 -u boxue  -p123456 \
	-NBe "select count(*), website_name from crawler.website \
		group by website_name;" 
	echo 
	echo
}
wait_for_hour
