#!/bin/bash
# record: 以一小时为间隔，访问MySQL数据库，查询website表的行数，并输出到对应的文件中

# 执行检测任务，
run(){
	while [[ true ]]; do
        wait_for_hour
        spy
        sleep 58m
	done

}

# 等待整点的到来
wait_for_hour(){

        # 每次休眠20秒，直到遇到整点
        while [[ true ]]; do
                if [[ "$(date +%M)" == "00" ]]; then
                      break
                else
                      sleep 20s

                fi
        done
        
		return 
}
# 将统计信息记录到文件中
spy(){

        format="%F %T"
        timestamp=$(date +"$format")

        sort_by_site $timestamp>> sort_by_site.log
        sort_by_channel $timestamp>> sort_by_channel.log
}
# 访问数据库，并查询按站点分类的数据量
sort_by_site(){
        echo $@
        for (( i=0; i<20; i++)); do echo -n "-"; done
        echo
        mysql -h 123.56.165.238 -u boxue  -p123456 \
        -NBe "select count(*), website_name from crawler.website \
                group by website_name;"
        echo
        echo

}
# 访问数据库，并查询按频道分类的数据量
sort_by_channel(){

        echo $@
        for (( i=0; i<20; i++)); do echo -n "-"; done
        echo
        mysql -h 123.56.165.238 -u boxue  -p123456 \
        -NBe "select count(*), channel_name from crawler.website \
                group by channel_name;"
        echo
        echo
}
run

